language: python
python:
- "3.5"

sudo: required
services:
  - docker

before_install:
  - sudo sysctl -w vm.max_map_count=262144
  - docker network create schulcloudserver_schulcloud-server-network
  - docker network create schulcloudcontent_default
  - docker-compose create
  - docker-compose start

install:
  - pip install schul_cloud_resources_server_tests==1.0.250

script:
  - sleep 30
  - docker-compose ps
  - docker-compose start
  - sleep 30
  - docker-compose ps
  - python3 -m schul_cloud_resources_server_tests.tests --url=http://localhost:4040/v1/ --basic=schulcloud-content-1:content-1 --basic=schulcloud-content-2:content-2 --noauth=false

after_failure:
  - docker-compose logs schulcloud-content
  - docker-compose ps
